---
- name: Install Software on Mac using Homebrew
  hosts: localhost 
  gather_facts: yes
  tasks:
    - name: Check if Homebrew is installed
      command: which brew
      register: homebrew_check
      ignore_errors: true

    - name: Install Homebrew if not present
      command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: homebrew_check.rc != 0

    - name: Update Homebrew
      homebrew: 
        update_homebrew: yes

    - name: Install 3rd party Homebrew software
      homebrew_tap:
        name: "{{ item }}"
        state: present
      loop:
        - oven-sh/bun

    - name: Install required software using Homebrew
      homebrew:
        name: "{{ item }}"
        state: present
      loop:
        - flutter
        - pnpm
        - postgresql@15
        - visual-studio-code
        - firefox
        - brave-browser
        - helix
        - podman
        - podman-compose
        - libpq
        - lazygit
        - logseq
        - aldente
        - signal
        - ansible-lint
        - spotify
        - jq
        - nvm
        - lossless-cut
        - sublime-text
        - maccy
